// The following embedded xml is for the editor and describes how the action can be edited:
// Supported types are: int, float, string, bool, color, vect3d, scenenode, texture, action
/*
    <action jsname="action_NKAdvancedDialog" description="NK - Advanced dialog v2.0">
        <property name="dialogName" type="string" default="" />
        <property name="nodeToShow" type="scenenode" default="" />
        <property name="interactionKey" type="string" default="69" />
        <property name="actionOnComplete" type="action" default="" />
        <property name="doNotGiveBackControl" type="bool" default="false" />
        <property name="typewriterEnabled" type="bool" default="true" />
        <property name="charDelayMs" type="int" default="140" />
        <property name="typewriterSoundNode" type="scenenode" default="" />
        <property name="action_1" type="action" default="" />
        <property name="action_2" type="action" default="" />
        <property name="action_3" type="action" default="" />
        <property name="action_4" type="action" default="" />
        <property name="action_5" type="action" default="" />
        <property name="action_6" type="action" default="" />
        <property name="action_7" type="action" default="" />
        <property name="action_8" type="action" default="" />
        <property name="action_9" type="action" default="" />
        <property name="action_10" type="action" default="" />
        <property name="action_11" type="action" default="" />
        <property name="action_12" type="action" default="" />
        <property name="action_13" type="action" default="" />
        <property name="action_14" type="action" default="" />
        <property name="action_15" type="action" default="" />
    </action>
*/

var okeEventHandler,OkeEventHandler=function(){this.eventHandlers=[],this.lastTime=null,this.currentTime=null,this.dt=null,this.nullCount=0};OkeEventHandler.prototype.updateDt=function(){return this.currentTime=Date.now(),this.dt=this.currentTime-this.lastTime,this.dt>200&&(this.dt=200),this.lastTime=this.currentTime,this},OkeEventHandler.prototype.registerEvent=function(e){this.eventHandlers.push(e)},OkeEventHandler.prototype.unregisterEvent=function(e){for(var t=0;t<this.eventHandlers.length;t++)if(this.eventHandlers[t]===e)return this.eventHandlers[t]=null,void(this.nullCount+=1)},OkeEventHandler.prototype.clearAllEvents=function(){this.eventHandlers.length=0,this.nullCount=0},OkeEventHandler.prototype.cleanUpDoneEvents=function(){if(this.nullCount>15){this.nullCount=0;for(var e=[],t=0;t<this.eventHandlers.length;t++)null!==this.eventHandlers[t]&&e.push(this.eventHandlers[t]);this.eventHandlers=e}},OkeEventHandler.prototype.executeEvents=function(){for(var e=0;e<this.eventHandlers.length;e++)null!==this.eventHandlers[e]&&this.eventHandlers[e](this.dt);return this},okeEventHandler||(print("Global event manager initialized!"),(okeEventHandler=new OkeEventHandler).lastTime=Date.now(),ccbRegisterOnFrameEvent((function(){okeEventHandler.updateDt().executeEvents().cleanUpDoneEvents()})));
var okeDialogs;

var NK_ADVANCED_DIALOG_VOWELS = ['a', 'A', 'e', 'E', 'y', 'Y', 'u', 'U', 'i', 'I', 'o', 'O'];

/**
 * @typedef DialogLine
 * @property { string } line
 * @property { string | null } speaker
 * @property { string | null } [preAction] - e.g. 'action_1', invoked when the line starts
 * @property { string | null } [postAction] - e.g. 'action_2', invoked when advancing to the next line
 * @property { number | null } [delay] - ms to wait before the next line; nodeToShow is hidden during this time
 */

action_NKAdvancedDialog = function () {}

action_NKAdvancedDialog.prototype.execute = function (node) {
    if (!this.nodeToShow || ccbGetSceneNodeProperty(this.nodeToShow, 'Type') === 'unknown') {
        print('NK Advanced dialog: nodeToShow is not set or invalid.');
        return;
    }

    if (!okeDialogs) {
        print('NK Advanced dialog: dialogs are not initialized. Have you added the extension generated by the Dialog app?')
    }

    var lines = okeDialogs[this.dialogName];

    if (!lines) {
        print('NK Advanced dialog: not able to find dialog "' + this.dialogName + '"');
    }
    if (!lines.length) {
        print('NK Advanced dialog: no dialog lines to show.');
        return;
    }

    var interactionKey = parseInt(this.interactionKey, 10);
    var lineActions = {};
    for (var a = 1; a <= 15; a++) {
        lineActions['action_' + a] = this['action_' + a];
    }
    var dialogFunc = this.buildDialogHandler(
        this.nodeToShow,
        lines,
        interactionKey,
        node,
        this.actionOnComplete,
        this.doNotGiveBackControl,
        this.typewriterEnabled,
        this.charDelayMs,
        this.typewriterSoundNode,
        lineActions
    );

    ccbSetSceneNodeProperty(this.nodeToShow, 'Visible', true);
    okeEventHandler.registerEvent(dialogFunc);
}

///**
// * Lines separated by ||, speaker and text by :|
// * Example: "Player|: Hello!||Cube|: Yes."
// * @param { string } dialogJson
// * @returns { DialogLine[] }
// */
//action_NKAdvancedDialog.prototype.parseDialogJson = function (dialogJson) {
//    if (!dialogJson || dialogJson === '') {
//        return [];
//    }
//
//    var SPEAKER_SEP = ':|';
//    var parts = dialogJson.split('||');
//    var lines = [];
//    for (var i = 0; i < parts.length; i++) {
//        if (parts[i] === '') {
//            continue;
//        }
//        var sepIndex = parts[i].indexOf(SPEAKER_SEP);
//        if (sepIndex !== -1) {
//            var line = parts[i].substring(sepIndex + SPEAKER_SEP.length);
//            if (line.length > 0 && line.charAt(0) === ' ') {
//                line = line.substring(1);
//            }
//            lines.push({
//                speaker: parts[i].substring(0, sepIndex),
//                line: line
//            });
//        } else {
//            lines.push({ speaker: null, line: parts[i] });
//        }
//    }
//    return lines;
//}

/**
 * @param { ccbNode } nodeToShow
 * @param { DialogLine[] } lines
 * @param { number } interactionKey
 * @param { ccbNode } node
 * @param { any } actionOnComplete
 * @param { boolean } doNotGiveBackControl
 * @param { boolean } typewriterEnabled
 * @param { number } charDelayMs
 * @param { ccbNode } typewriterSoundNode
 * @param { Object.<string, any> } lineActions - maps 'action_1'..'action_15' to editor action properties
 */
action_NKAdvancedDialog.prototype.buildDialogHandler = function (
    nodeToShow,
    lines,
    interactionKey,
    node,
    actionOnComplete,
    doNotGiveBackControl,
    typewriterEnabled,
    charDelayMs,
    typewriterSoundNode,
    lineActions
) {
    var hasTypewriterSound = typewriterSoundNode &&
        ccbGetSceneNodeProperty(typewriterSoundNode, 'Type') !== 'unknown';

    function playTypewriterSound() {
        if (hasTypewriterSound) {
            ccbSetSceneNodeProperty(typewriterSoundNode, 'PlayMode', 'nothing');
            ccbSetSceneNodeProperty(typewriterSoundNode, 'PlayMode', 'play_once');
        }
    }
    var lineIndex = 0;
    var curText = '';
    var phraseCompleted = false;
    var lastCharTime = 0;
    var waitingForDelay = false;
    var delayUntil = 0;

    function invokeLineAction(actionRef) {
        if (!actionRef) {
            return;
        }
        var action = typeof actionRef === 'string' ? lineActions[actionRef] : actionRef;
        if (action) {
            ccbInvokeAction(action, node);
        }
    }

    function getSpeakerPrefix(entry) {
        return entry.speaker ? entry.speaker + ':\r\n\r\n' : '';
    }

    function finishDialog() {
        okeEventHandler.unregisterEvent(inner);
        ccbSetSceneNodeProperty(nodeToShow, 'Visible', false);
        if (!doNotGiveBackControl && typeof interactablesManager !== 'undefined') {
            interactablesManager.scheduleTurnOn();
        }
        if (actionOnComplete) {
            ccbInvokeAction(actionOnComplete, node);
        }
    }

    function startLine(entry) {
        invokeLineAction(entry.preAction);
        var speakerPrefix = getSpeakerPrefix(entry);
        curText = speakerPrefix;
        phraseCompleted = !typewriterEnabled;
        lastCharTime = Date.now();
        if (phraseCompleted) {
            curText = speakerPrefix + entry.line;
        }
        ccbSetSceneNodeProperty(nodeToShow, 'Text', curText);
    }

    function advanceToNextLine() {
        var entry = lines[lineIndex];
        invokeLineAction(entry.postAction);

        var delayMs = entry.delay;
        if (delayMs != null && delayMs > 0) {
            ccbSetSceneNodeProperty(nodeToShow, 'Visible', false);
            waitingForDelay = true;
            delayUntil = Date.now() + delayMs;
            return;
        }

        lineIndex += 1;
        if (lineIndex >= lines.length) {
            finishDialog();
            return;
        }
        startLine(lines[lineIndex]);
    }

    startLine(lines[0]);

    function inner() {
        ccbSetMousePos(ccbGetScreenWidth() / 2, ccbGetScreenHeight() / 2);

        if (waitingForDelay) {
            if (Date.now() >= delayUntil) {
                waitingForDelay = false;
                lineIndex += 1;
                if (lineIndex >= lines.length) {
                    finishDialog();
                    return;
                }
                ccbSetSceneNodeProperty(nodeToShow, 'Visible', true);
                startLine(lines[lineIndex]);
            }
            return;
        }

        var entry = lines[lineIndex];
        var speakerPrefix = getSpeakerPrefix(entry);
        var fullText = speakerPrefix + entry.line;
        var now = Date.now();

        if (!phraseCompleted) {
            if (typeof isJustPressed === 'function' && isJustPressed(interactionKey)) {
                curText = fullText;
                phraseCompleted = true;
            } else if (lastCharTime + charDelayMs < now) {
                lastCharTime = now;
                var lineIndexInText = curText.length - speakerPrefix.length;
                var charToAdd = entry.line[lineIndexInText];
                if (charToAdd === undefined) {
                    phraseCompleted = true;
                } else {
                    curText += charToAdd;
                    phraseCompleted = curText.length === fullText.length;
                    if (hasTypewriterSound && NK_ADVANCED_DIALOG_VOWELS.indexOf(charToAdd) === -1) {
                        playTypewriterSound();
                    }
                }
            }
            ccbSetSceneNodeProperty(nodeToShow, 'Text', curText);
        } else if (typeof isJustPressed === 'function' && isJustPressed(interactionKey)) {
            if (lineIndex >= lines.length - 1) {
                invokeLineAction(entry.postAction);
                finishDialog();
                return;
            }
            advanceToNextLine();
        }
    }

    return inner;
}
