// The following embedded xml is for the editor and describes how the action can be edited:
// Supported types are: int, float, string, bool, color, vect3d, scenenode, texture, action
/*
    <action jsname="action_NKBranchingDialog" description="NK - Branching dialog v1.0">
        <property name="dialogName" type="string" default="" />
        <property name="nodeToShow" type="scenenode" default="" />
        <property name="responseNode_1" type="scenenode" default="" />
        <property name="responseNode_2" type="scenenode" default="" />
        <property name="responseNode_3" type="scenenode" default="" />
        <property name="responseNode_4" type="scenenode" default="" />
        <property name="interactionKey" type="string" default="69" />
        <property name="actionOnComplete" type="action" default="" />
        <property name="doNotGiveBackControl" type="bool" default="false" />
        <property name="typewriterEnabled" type="bool" default="true" />
        <property name="charDelayMs" type="int" default="140" />
        <property name="typewriterSoundNode" type="scenenode" default="" />
        <property name="action_1" type="action" default="" />
        <property name="action_2" type="action" default="" />
        <property name="action_3" type="action" default="" />
        <property name="action_4" type="action" default="" />
        <property name="action_5" type="action" default="" />
        <property name="action_6" type="action" default="" />
        <property name="action_7" type="action" default="" />
        <property name="action_8" type="action" default="" />
        <property name="action_9" type="action" default="" />
        <property name="action_10" type="action" default="" />
        <property name="action_11" type="action" default="" />
        <property name="action_12" type="action" default="" />
        <property name="action_13" type="action" default="" />
        <property name="action_14" type="action" default="" />
        <property name="action_15" type="action" default="" />
    </action>
*/

var okeEventHandler,OkeEventHandler=function(){this.eventHandlers=[],this.lastTime=null,this.currentTime=null,this.dt=null,this.nullCount=0};OkeEventHandler.prototype.updateDt=function(){return this.currentTime=Date.now(),this.dt=this.currentTime-this.lastTime,this.dt>200&&(this.dt=200),this.lastTime=this.currentTime,this},OkeEventHandler.prototype.registerEvent=function(e){this.eventHandlers.push(e)},OkeEventHandler.prototype.unregisterEvent=function(e){for(var t=0;t<this.eventHandlers.length;t++)if(this.eventHandlers[t]===e)return this.eventHandlers[t]=null,void(this.nullCount+=1)},OkeEventHandler.prototype.clearAllEvents=function(){this.eventHandlers.length=0,this.nullCount=0},OkeEventHandler.prototype.cleanUpDoneEvents=function(){if(this.nullCount>15){this.nullCount=0;for(var e=[],t=0;t<this.eventHandlers.length;t++)null!==this.eventHandlers[t]&&e.push(this.eventHandlers[t]);this.eventHandlers=e}},OkeEventHandler.prototype.executeEvents=function(){for(var e=0;e<this.eventHandlers.length;e++)null!==this.eventHandlers[e]&&this.eventHandlers[e](this.dt);return this},okeEventHandler||(print("Global event manager initialized!"),(okeEventHandler=new OkeEventHandler).lastTime=Date.now(),ccbRegisterOnFrameEvent((function(){okeEventHandler.updateDt().executeEvents().cleanUpDoneEvents()})));
var okeDialogs, okeBranchingDialogSelection;

var NK_BRANCHING_DIALOG_VOWELS = ['a', 'A', 'e', 'E', 'y', 'Y', 'u', 'U', 'i', 'I', 'o', 'O'];

/**
 * @typedef BranchingLineNode
 * @property { string } kind - 'line'
 * @property { string } line
 * @property { string | null } speaker
 * @property { string | null } [preAction]
 * @property { string | null } [postAction]
 * @property { number | null } [delay]
 */

/**
 * @typedef BranchingResponseNode
 * @property { string } kind - 'response'
 * @property { string } text
 */

/**
 * @typedef BranchingDialog
 * @property { string } kind - 'branching'
 * @property { Object.<string, BranchingLineNode|BranchingResponseNode> } nodes
 * @property { Array.<{ from: string, fromHandle: string, to: string }> } edges
 * @property { string } entry
 */

action_NKBranchingDialog = function () {}

action_NKBranchingDialog.prototype.execute = function (node) {
    if (!this.nodeToShow || ccbGetSceneNodeProperty(this.nodeToShow, 'Type') === 'unknown') {
        print('NK Branching dialog: nodeToShow is not set or invalid.');
        return;
    }

    if (!okeDialogs) {
        print('NK Branching dialog: dialogs are not initialized. Have you added the extension generated by the Dialog app?');
        return;
    }

    var dialog = okeDialogs[this.dialogName];

    if (!dialog) {
        print('NK Branching dialog: not able to find dialog "' + this.dialogName + '"');
        return;
    }
    if (dialog.kind !== 'branching' || !dialog.nodes || !dialog.edges || !dialog.entry) {
        print('NK Branching dialog: dialog "' + this.dialogName + '" is not a valid branching dialog.');
        return;
    }

    var entryNode = dialog.nodes[dialog.entry];
    if (!entryNode || entryNode.kind !== 'line') {
        print('NK Branching dialog: entry node is missing or not a line.');
        return;
    }

    var interactionKey = parseInt(this.interactionKey, 10);
    var lineActions = {};
    for (var a = 1; a <= 15; a++) {
        lineActions['action_' + a] = this['action_' + a];
    }

    var responseNodes = [
        this.responseNode_1,
        this.responseNode_2,
        this.responseNode_3,
        this.responseNode_4
    ];

    okeBranchingDialogSelection = -1;

    var dialogFunc = this.buildDialogHandler(
        this.nodeToShow,
        dialog,
        dialog.entry,
        responseNodes,
        interactionKey,
        node,
        this.actionOnComplete,
        this.doNotGiveBackControl,
        this.typewriterEnabled,
        this.charDelayMs,
        this.typewriterSoundNode,
        lineActions
    );

    ccbSetSceneNodeProperty(this.nodeToShow, 'Visible', true);
    okeEventHandler.registerEvent(dialogFunc);
}

/**
 * @param { BranchingDialog } dialog
 * @param { string } lineNodeId
 * @returns { Array.<{ slotIndex: number, nodeId: string, text: string }> }
 */
action_NKBranchingDialog.prototype.getResponseOptions = function (dialog, lineNodeId) {
    var options = [];
    var edges = dialog.edges;
    var nodes = dialog.nodes;
    var i;
    var e;
    var handle;
    var idx;
    var responseNode;

    for (i = 0; i < edges.length; i++) {
        e = edges[i];
        if (e.from !== lineNodeId) {
            continue;
        }
        handle = e.fromHandle;
        if (!handle || handle.indexOf('out-') !== 0) {
            continue;
        }
        idx = parseInt(handle.substring(4), 10);
        if (isNaN(idx) || idx < 0 || idx > 3) {
            continue;
        }
        responseNode = nodes[e.to];
        if (responseNode && responseNode.kind === 'response') {
            options.push({
                slotIndex: idx,
                nodeId: e.to,
                text: responseNode.text
            });
        }
    }

    options.sort(function (a, b) {
        return a.slotIndex - b.slotIndex;
    });

    return options;
}

/**
 * @param { BranchingDialog } dialog
 * @param { string } responseNodeId
 * @returns { { nodeId: string, entry: BranchingLineNode } | null }
 */
action_NKBranchingDialog.prototype.getNextLineAfterResponse = function (dialog, responseNodeId) {
    var edges = dialog.edges;
    var nodes = dialog.nodes;
    var i;
    var e;
    var next;

    for (i = 0; i < edges.length; i++) {
        e = edges[i];
        if (e.from === responseNodeId && e.fromHandle === 'out') {
            next = nodes[e.to];
            if (next && next.kind === 'line') {
                return { nodeId: e.to, entry: next };
            }
        }
    }

    return null;
}

/**
 * @param { ccbNode } nodeToShow
 * @param { BranchingDialog } dialog
 * @param { string } startLineNodeId
 * @param { ccbNode[] } responseNodes - up to 4 scene nodes for choices
 * @param { number } interactionKey
 * @param { ccbNode } node
 * @param { any } actionOnComplete
 * @param { boolean } doNotGiveBackControl
 * @param { boolean } typewriterEnabled
 * @param { number } charDelayMs
 * @param { ccbNode } typewriterSoundNode
 * @param { Object.<string, any> } lineActions
 */
action_NKBranchingDialog.prototype.buildDialogHandler = function (
    nodeToShow,
    dialog,
    startLineNodeId,
    responseNodes,
    interactionKey,
    node,
    actionOnComplete,
    doNotGiveBackControl,
    typewriterEnabled,
    charDelayMs,
    typewriterSoundNode,
    lineActions
) {
    var self = this;
    var hasTypewriterSound = typewriterSoundNode &&
        ccbGetSceneNodeProperty(typewriterSoundNode, 'Type') !== 'unknown';

    function playTypewriterSound() {
        if (hasTypewriterSound) {
            ccbSetSceneNodeProperty(typewriterSoundNode, 'PlayMode', 'nothing');
            ccbSetSceneNodeProperty(typewriterSoundNode, 'PlayMode', 'play_once');
        }
    }

    var currentLineNodeId = startLineNodeId;
    var currentLineEntry = dialog.nodes[startLineNodeId];
    var curText = '';
    var phraseCompleted = false;
    var lastCharTime = 0;
    var waitingForDelay = false;
    var delayUntil = 0;
    var phase = 'line';
    var pendingNextLine = null;

    function invokeLineAction(actionRef) {
        if (!actionRef) {
            return;
        }
        var action = typeof actionRef === 'string' ? lineActions[actionRef] : actionRef;
        if (action) {
            ccbInvokeAction(action, node);
        }
    }

    function getSpeakerPrefix(entry) {
        return entry.speaker ? entry.speaker + ':\r\n\r\n' : '';
    }

    function hideAllResponseNodes() {
        var r;
        var rn;
        for (r = 0; r < 4; r++) {
            rn = responseNodes[r];
            if (rn && ccbGetSceneNodeProperty(rn, 'Type') !== 'unknown') {
                ccbSetSceneNodeProperty(rn, 'Visible', false);
            }
        }
    }

    function showResponseChoices(options) {
        var r;
        var rn;
        var o;
        var opt = null;

        hideAllResponseNodes();
        for (r = 0; r < 4; r++) {
            rn = responseNodes[r];
            if (!rn || ccbGetSceneNodeProperty(rn, 'Type') === 'unknown') {
                continue;
            }
            opt = null;
            for (o = 0; o < options.length; o++) {
                if (options[o].slotIndex === r) {
                    opt = options[o];
                    break;
                }
            }
            if (opt) {
                ccbSetSceneNodeProperty(rn, 'Text', opt.text);
                ccbSetSceneNodeProperty(rn, 'Visible', true);
            }
        }
        okeBranchingDialogSelection = -1;
    }

    function finishDialog() {
        okeEventHandler.unregisterEvent(inner);
        hideAllResponseNodes();
        ccbSetSceneNodeProperty(nodeToShow, 'Visible', false);
        okeBranchingDialogSelection = -1;
        if (!doNotGiveBackControl && typeof interactablesManager !== 'undefined') {
            interactablesManager.scheduleTurnOn();
        }
        if (actionOnComplete) {
            ccbInvokeAction(actionOnComplete, node);
        }
    }

    function startLine(lineId, entry) {
        currentLineNodeId = lineId;
        currentLineEntry = entry;
        phase = 'line';
        hideAllResponseNodes();
        invokeLineAction(entry.preAction);
        var speakerPrefix = getSpeakerPrefix(entry);
        curText = speakerPrefix;
        phraseCompleted = !typewriterEnabled;
        lastCharTime = Date.now();
        if (phraseCompleted) {
            curText = speakerPrefix + entry.line;
        }
        ccbSetSceneNodeProperty(nodeToShow, 'Visible', true);
        ccbSetSceneNodeProperty(nodeToShow, 'Text', curText);
    }

    function beginDelayThenContinue(delayMs, nextLine) {
        pendingNextLine = nextLine;
        ccbSetSceneNodeProperty(nodeToShow, 'Visible', false);
        hideAllResponseNodes();
        waitingForDelay = true;
        delayUntil = Date.now() + delayMs;
        phase = 'delay';
    }

    function leaveCurrentLine(nextLine) {
        var entry = currentLineEntry;
        invokeLineAction(entry.postAction);

        var delayMs = entry.delay;
        if (delayMs != null && delayMs > 0) {
            beginDelayThenContinue(delayMs, nextLine);
            return;
        }

        if (nextLine) {
            startLine(nextLine.nodeId, nextLine.entry);
        } else {
            finishDialog();
        }
    }

    function enterChoicePhase() {
        var options = self.getResponseOptions(dialog, currentLineNodeId);
        if (!options.length) {
            return false;
        }
        phase = 'choices';
        showResponseChoices(options);
        return true;
    }

    function applySelection(selectionIndex) {
        var options = self.getResponseOptions(dialog, currentLineNodeId);
        var slotIndex = selectionIndex - 1;
        var i;
        var chosen = null;

        for (i = 0; i < options.length; i++) {
            if (options[i].slotIndex === slotIndex) {
                chosen = options[i];
                break;
            }
        }

        okeBranchingDialogSelection = -1;
        hideAllResponseNodes();

        if (!chosen) {
            return;
        }

        var nextLine = self.getNextLineAfterResponse(dialog, chosen.nodeId);
        leaveCurrentLine(nextLine);
    }

    startLine(startLineNodeId, currentLineEntry);

    function inner() {
        // ccbSetMousePos(ccbGetScreenWidth() / 2, ccbGetScreenHeight() / 2);
        ccbSetCursorVisible(true);

        if (waitingForDelay) {
            if (Date.now() >= delayUntil) {
                waitingForDelay = false;
                var next = pendingNextLine;
                pendingNextLine = null;
                if (next) {
                    startLine(next.nodeId, next.entry);
                } else {
                    finishDialog();
                }
            }
            return;
        }

        if (phase === 'choices') {
            var sel = okeBranchingDialogSelection;
            if (sel >= 1 && sel <= 4) {
                applySelection(sel);
            }
            return;
        }

        var entry = currentLineEntry;
        var speakerPrefix = getSpeakerPrefix(entry);
        var fullText = speakerPrefix + entry.line;
        var now = Date.now();

        if (!phraseCompleted) {
            if (typeof isJustPressed === 'function' && isJustPressed(interactionKey)) {
                curText = fullText;
                phraseCompleted = true;
            } else if (lastCharTime + charDelayMs < now) {
                lastCharTime = now;
                var lineIndexInText = curText.length - speakerPrefix.length;
                var charToAdd = entry.line[lineIndexInText];
                if (charToAdd === undefined) {
                    phraseCompleted = true;
                } else {
                    curText += charToAdd;
                    phraseCompleted = curText.length === fullText.length;
                    if (hasTypewriterSound && NK_BRANCHING_DIALOG_VOWELS.indexOf(charToAdd) === -1) {
                        playTypewriterSound();
                    }
                }
            }
            ccbSetSceneNodeProperty(nodeToShow, 'Text', curText);
            return;
        }

        var options = self.getResponseOptions(dialog, currentLineNodeId);
        if (options.length > 0) {
            enterChoicePhase();
            return;
        }

        if (typeof isJustPressed === 'function' && isJustPressed(interactionKey)) {
            leaveCurrentLine(null);
        }
    }

    return inner;
}
